version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/spleeter
    steps:
      - checkout
      - run:
          name: install ffmpeg
          command: sudo apt-get update && sudo apt-get install ffmpeg
      - run:
          name: install spleeter
          command: sudo pip install .
      - run:
          name: test separation
          command: python -m spleeter separate -i audio_example.mp3 -o .
  upload:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:  
          name: package
          command: python setup.py bdist
      - run:
          name: upload to PyPi
          command: pip install twine --user && twine upload dist/*
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - upload:
          filters:
            branches:
              only:
                - master
          requires:
            - test