name: conda
on:
  push:
    branches:
      - master
env:
  ANACONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
  ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
jobs:
  package-and-deploy:
    strategy:
      matrix:
        platform: [cpu, gpu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install conda-build
          conda install anaconda-client
      - name: Build package
        shell: bash -l {0}
        run: cd conda/${{ matrix.platform }} && conda-build spleeter
