name: conda
on:
  push:
    branches:
      - master
env:
  ANACONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
  ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
jobs:
  package-and-deploy:
    strategy:
      matrix:
        platform: [cpu, gpu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup conda-build
        run: $CONDA/bin/conda install conda-build
      - name: Setup anaconda-client
        run: $CONDA/bin/conda install anaconda-client
      - name: Build package
        run: cd conda/${{ matrix.platform }} && $CONDA/bin/conda-build spleeter
