name: conda
on:
  push:
    branches:
      - master
env:
  ANACONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
  ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
jobs:
  package-and-deploy:
    strategy:
      matrix:
        package: [spleeter]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          $CONDA/bin/conda install conda-build
          $CONDA/bin/conda install anaconda-client
      - name: Build package
        run: cd conda/${{ matrix.package }} && $CONDA/bin/conda-build spleeter
