name: pypi
on:
  pull_request:
    types:
      - closed
    branches:
      - master
env:
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
jobs:
  package-and-deploy:
    strategy:
      matrix:
        platform: [cpu, gpu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: dist
          key: sdist-${{ matrix.platform }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            sdist-${{ matrix.platform }}-${{ hashFiles('**/setup.py') }}
            sdist-${{ matrix.platform }}
            sdist-
      - if: ${{ matrix.platform }} == 'cpu'
        name: Package CPU distribution
        run: make build
      - if: ${{ matrix.platform }} == 'gpu'
        name: Package GPU distribution
        run: make build-gpu
      - name: Deploy to pypi
        run: make deploy